### ISSUE TITLE
[Bug] Internal server error on any endpoint on official instance

### ISSUE THREAD

**Issue by Davilarek** [PrivacyDevel/freexiv#5]
Hello,
Lately, the server throws internal server error (500) on any endpoint, including homepage on the official instance.
Is there any information about this issue?

**Comment by PrivacyDevel** [comment]
Hi!
I assume the underlying account that my instance has been using has been terminated. I replaced it a few days ago and it started working again for a little while. I did not confirm my email address tho, which presumably lead to that account being suspended as well. I just created a new one that I actually confirmed this time. I hope this one will last a little longer this time. :)
